# ==========================================================================
# Configuración General del Proyecto
# ==========================================================================
quarkus.application.name=ecommerce-api
quarkus.http.port=8080
# ==========================================================================
# Configuración de la Base de Datos (PostgreSQL)
# ==========================================================================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=ecommerce_user
quarkus.datasource.password=ecommerce_password
# URL por defecto (se usará en local y en %dev)
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ecommerce_db
# Mostrar consultas SQL en consola (Útil en desarrollo)
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.database.generation=update
# ==========================================================================
# Configuración de Seguridad JWT (Llaves Asimétricas RSA)
# ==========================================================================
mp.jwt.verify.issuer=https://epn.edu.ec/ecommerce
# Ubicación de las llaves para desarrollo/producción estándar
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
# ==========================================================================
# Swagger UI & SmallRye OpenAPI
# ==========================================================================
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.title=EPN - E-commerce API Grupo 1
quarkus.smallrye-openapi.path=/openapi
mp.openapi.scan.disable=false
# ==========================================================================
# Semilla de Datos
# ==========================================================================
app.admin.email=admin@epn.edu.ec
app.admin.password=ChangeMe123!
# ==========================================================================
# CONFIGURACIÓN EXCLUSIVA PARA ENTORNO DE PRUEBAS (%test)
# ==========================================================================
# Desactivar Dev Services para no usar Testcontainers
%test.quarkus.datasource.devservices=false
%test.quarkus.datasource.db-kind=postgresql
# Apuntar directamente al Docker local de PostgreSQL
%test.quarkus.datasource.username=ecommerce_user
%test.quarkus.datasource.password=ecommerce_password
%test.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ecommerce_db
# Configuración de llaves mockeadas para los tests de seguridad
%test.mp.jwt.verify.publickey={"keys":[{"kty":"RSA","n":"u1W_o9jY","e":"AQAB","kid":"2026-test"}]}
# Se comentan las ubicaciones físicas en test para evitar conflictos con el JWK de arriba
#%test.smallrye.jwt.sign.key.location=privateKey.pem
#%test.mp.jwt.verify.publickey.location=publicKey.pem
